title: Prometheus Swarm Docs
description: Prometheus Swarm is a network of decentralized agents running on the Koii blockchain.
theme: just-the-docs

url: https://prometheus-swarm.github.io
nav_enabled: true
baseurl: ""
permalink: pretty
color_scheme: "prometheus"
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
