title: Prometheus Swarm Docs
description: Prometheus Swarm is a network of decentralized agents running on the Koii blockchain.
theme: just-the-docs

url: https://prometheus-swarm.github.io
nav_enabled: true
baseurl: ""
permalink: pretty
color_scheme: "prometheus"
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"

# Define collections for navigation structure
collections:
  # Introduction (README.md at root)
  introduction:
    output: true
    permalink: /:collection/:path/
  # Our Origin Story section
  about:
    output: true
    permalink: /:collection/:path/
  # Guides section
  guides:
    output: true
    permalink: /:collection/:path/
  # How it works section
  how-it-works:
    output: true
    permalink: /:collection/:path/
  # Existing docs content (preserved)
  docs:
    output: true
    permalink: /:collection/:path/

# Set the order of collections in navigation
collections_dir: .
nav_sort: case_sensitive

# Just the Docs navigation settings
aux_links:
  "Prometheus Swarm on GitHub":
    - "//github.com/Prometheus-Swarm"

# Exclude these files from being included in collections
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Include folders that Jekyll might otherwise ignore
include:
  - about
  - guides
  - how-it-works

# Default settings for pages
defaults:
  # Root pages (like README.md)
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
  # Introduction collection (should include README.md)
  - scope:
      path: ""
      type: introduction
    values:
      layout: "default"
      nav_order: 1
  # About collection
  - scope:
      path: "about"
      type: about
    values:
      layout: "default"
      nav_order: 2
  # Guides collection
  - scope:
      path: "guides"
      type: guides
    values:
      layout: "default"
      nav_order: 3
  # How it works collection
  - scope:
      path: "how-it-works"
      type: how-it-works
    values:
      layout: "default"
      nav_order: 4
  # Docs collection (existing content)
  - scope:
      path: "docs"
      type: docs
    values:
      layout: "default"
      nav_order: 5

# collections: # This was a thought, but holding off for now.
# main_docs:
# output: true
# order:
#       - README.md
#       - about/origin.md
#       - guides/for-creators.md
#       - guides/for-developers.md
#       - guides/for-enterprise.md
#       - how-it-works/architecture.md
#       - how-it-works/usage-process.md
#       - how-it-works/quality-assurance.md
