title: Prometheus Swarm Docs
description: Prometheus Swarm is a network of decentralized agents running on the Koii blockchain.
theme: just-the-docs

url: https://prometheus-swarm.github.io
nav_enabled: true
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
